variables:
  GIT_SUBMODULE_STRATEGY: recursive

.template: &template
  before_script:
    - echo "Installing potential dependencies..."


  script:
    - cmake -E make_directory build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOCS=OFF ..
    - cmake --build .
    - ctest

build-and-test:gcc:
  image: conanio/gcc9
  <<: *template

build-and-test:clang:
  image: conanio/clang10
  <<: *template

generate-coverage-report:
  image: conanio/gcc7
  <<: *template
  script:
    - sudo apt-get update
    - sudo apt-get install -yy lcov
    - cmake -E make_directory build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" -DBUILD_DOCS=OFF ..
    - cmake --build .
    - ctest
    - cd ..
    - lcov --directory ./build/src --capture --output-file coverage.info
    - bash <(curl --connect-timeout 10 --retry 5 -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
