#ifndef MCMCEXAMPLEPROJECT_CONFIG_H_IN
#define MCMCEXAMPLEPROJECT_CONFIG_H_IN

#define PROJECT_NAME "ONModelGPU"
#define CLUSTER_MODE "local"
#define PYTHON_SCRIPTS_PATH "./python_scripts"

#endif // MCMCEXAMPLEPROJECT_CONFIG_H_IN
